### ISSUE TITLE
Går ej att ta bort API-nycklar

### ISSUE THREAD

**Issue by camipe** [mc22ft/Webbramverk#1]
När jag försöker ta bort applikationer/api-nycklar så kraschar applikation på grund av att current_user metoden försöker ta ut en användare med :id parametern i URL:en (som i det här fallet refererar till en API-nyckels ID inte en användares ID). Se bild.
![skarmavbild 2016-02-08 kl 11 48 08](https://cloud.githubusercontent.com/assets/6189745/12889155/ec504d88-ce7d-11e5-8d75-4bb3593488b2.png)

**Comment by mc22ft** [comment]
Jag hade lagt på before_actions som spärrade funktionen för att ta bort en api nyckel. Testade inte fult ut innan jag lämnade in
