### ISSUE TITLE
Ingen kontroll av api key

### ISSUE THREAD

**Issue by olafranzen** [mc22ft/Webbramverk#10]
Kan inte se att kontroll görs att en api-key skickas med i anropen mot api:et, bara kontroll att man är auktoriserad som creator. Finns en funktion api_key i application_controller men kan inte se att den används?

**Comment by mc22ft** [comment]
Jag ber om ursäkt för min dåliga rensning av kod. Det är samma function som heter restrict_access i api_controller. Ändrar namn på restrict_access (det anv i railscast) till api_key och rensar lite till!!!
