### ISSUE TITLE
Event skapas trots felaktiga parametrar

### ISSUE THREAD

**Issue by olafranzen** [mc22ft/Webbramverk#12]
Skickade en POST till events utan lat och long paramterar, då skapas eventet ändå utan några felmeddelanden.

**Comment by mc22ft** [comment]
Har kollat på detta men förstår inte riktigt vad felet ligger? Det är bara lat och long som går att skicka in tomma fält till??? Tar gärna emot tips på hur jag kan göra?

**Comment by mc22ft** [comment]
Håller den öppet lite till om du kunde veta vad felet var? 

Bra jobbat och tack för alla issues. Jag blev lite klokare på köpet! :)

**Comment by olafranzen** [comment]
Hoppas du inte tyckte ja var för hård, mycket var ju bra men man tar ju bara upp issues man hittar :)

Ang detta så handlar det nog om validering på något sätt, kanske kolla att Position kan skapas och sparas innan Event skapas? Blev lite osäker exakt hur det löses eftersom du ju har validering av long o lat i Position men troligen så lyckas den inte skapas i events_controller men går ändå vidare till att skapa Event? 
Beror väl på om det är ett krav också att Position ska finnas för ett Event.
Hoppas det löser sig, lärde mig också en del av att kolla någon annans lösning :)

**Comment by mc22ft** [comment]
Jag tycker du var rätt på sak och rättvis.

Kollade lite på hur position skapas och sparas. Löste sig inte just med några enklare justeringar men håller det på uppsikt om det skulle behövas framöver. Kommer säkert kunnas valideras i angular appen :)
Tack för bra feedback och issues!
