### ISSUE TITLE
500 error vid POST till events med saknande parametrar

### ISSUE THREAD

**Issue by olafranzen** [mc22ft/Webbramverk#13]
Om man t.ex inte skickar med creator_id så får man inget json tillbaka utan ett fel från servern. Behöver nog byta ut "rescue ActiveRecord::RecordNotFound" till att fånga andra feltyper i events_controller -> create

**Comment by mc22ft** [comment]
Har tagit bort att man kan skicka in creator_id. 

Jag har funderat och kollat mycket på felhanteringen idag. Hade inte koll på att använda find_by_id istället bara för find överskuggade ActiveRecord::RecordNotFound. Nu fungerar det bättre.
