### ISSUE TITLE
Går inte koppla flera tags till ett event

### ISSUE THREAD

**Issue by olafranzen** [mc22ft/Webbramverk#14]
Kan inte se något sätt att koppla flera taggar till ett event (inte genom create eller update i events_controller). Går ju internt men inte genom anropen till API:t.

**Comment by mc22ft** [comment]
Nu ska det fungera så att det inte blir dubbla taggar i db. Jag har inte funktionen att man kan skicka in fler taggar samtidigt tror inte det var ett krav. Men får se om det behövs i sista angularJS labb uppdaterar i så fall.
