### ISSUE TITLE
Instructions are not working

### ISSUE THREAD

**Issue by OskarKlintrot** [mc22ft/Webbramverk#19]
Since the instructions are not working if Webstorms and Rubymine is not correctly setup according to the project and there is no info in the instructions on how to setup Webstorms and Rubymine I will not run the project. I will just be looking at the code. If you want more thorough feedback I suggest that you make it possible to run the project. I have had to setup my own server on vagrant on both the previous peer review's and I'm not doing it again. If you you have a perfectly fine working [Vagrant setup here](https://github.com/OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk/), it's `Vagrantfile` and `bootstrap.sh` that you need. For the client a simple node server would work perfectly.

![image](https://cloud.githubusercontent.com/assets/6783879/14403051/8ed3b06e-fe48-11e5-8ff7-3a3b187ff408.png)

**Comment by mc22ft** [comment]
I agree with you that the installation instructions on Angular application was not so good. I forgot to download Angular application from Github to test so it worked. My bad. I have done this and update instructions. Bower missing dependency was wrong.
Ruby application: it has been peer-reviewed before so it should work.
But it was sad that you could not start up the application.

**Comment by OskarKlintrot** [comment]
It dosen't help just to install Bower! Bower just handles the dependencies but somehow you need to run the application as well. I already have Bower installed but there is no config file for Bower in the project, just the vendors and they should not be added to git. I finally got it up and running with Webstorms but it looks like we are using different versions because your instructions dosen't match my version of Webstorms at all. Webstorms are using it's own built-in server and that works but when I try to use Node it dosen't work. I really think you should take your time and try to learn how to use the tools without Webstorms. This is something that shouldn't be an issue this late in the studies. Using NPM, Bower, Vagrant etc. should be second nature by now!

**Comment by OskarKlintrot** [comment]
Just imagine deploying this project when it can't run on a regular server!

**Comment by OskarKlintrot** [comment]
Oh, and you should NEVER use `sudo` to get `npm install` working! You should fix your system instead!
