### ISSUE TITLE
Menyn beter sig konstigt vid ändring av webbläsarens storlek

### ISSUE THREAD

**Issue by camipe** [mc22ft/Webbramverk#2]
Om jag t.ex. laddar sidan med litet fönster och sedan förstorar det och sedan förminskar det igen eller laddar med stort fönster och sedan förminskar och sedan förstorar det så beter den sig inte rätt och täcker ibland över vissa element längre ner på sidan. Se bild.
![skarmavbild 2016-02-08 kl 11 45 54](https://cloud.githubusercontent.com/assets/6189745/12889337/b2e1166c-ce7e-11e5-9621-380714663059.png)

**Comment by mc22ft** [comment]
Jag hade hade lite "skit" i koden som gjorde att det blev som ovan på bilden. Över "Hem" på bilden syns lite vagt två | | som ställde till det.
