### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by OskarKlintrot** [mc22ft/Webbramverk#21]
Comments are sometimes very redundant since the code itself already describes what is going on. The grammar and spelling is not so good many times. There is also a lot of Swenglish in the comments. Sometimes it's very hard to understand what they are trying to say.

``` Javascript
// Creates a intern Resource-object that is filled with data (depending on what the server gets us)
var Resource = function(data) {
    // Configuerar objectet enligt den data som kommer in - Allt är json
    angular.extend(this, data);
};
```

``` Javascript
// Ordinaiery http-call
var req = {
    method: 'GET',
    url: APIConstant.url +collectionName, // this is the entry point in my example
    headers: {
        'Accept': APIConstant.format,
        "Authorization" : APIConstant.key
    }
};
```

``` Javascript
// OK this is maybe a clumpsy way to do this and shows a problem with REST and HATEOAS
// are we using the url provided by the call- The HATEOAS way
```

**Comment by mc22ft** [comment]
I understand what you mean. I have not cleaned my application that I usually do. I usually save quite a lot of comments on my projects so I can come back and understand more easily for the future.
