### ISSUE TITLE
ResourceService don't appear to be particularly generalised

### ISSUE THREAD

**Issue by OskarKlintrot** [mc22ft/Webbramverk#22]
Something named `ResourceService` sounds like it would be very generalised but there seem to stuff very closely related to something. Maybe that specific logic should live in the other services that is using `ResourceService`? And what's the problem with REST and HATEOAS?

``` Javascript
// OK this is maybe a clumpsy way to do this and shows a problem with REST and HATEOAS
// are we using the url provided by the call- The HATEOAS way
if(resourceInfo.hasOwnProperty('url')) {
    url = resourceInfo.url;
}
else if(resourceInfo.hasOwnProperty('instanceName') && resourceInfo.hasOwnProperty('id')) { // or we using a fall back (item => is an id)
    url = APIConstant.url +resourceInfo.instanceName +"/" +resourceInfo.id
}
else {
    return false;
}
```

**Comment by mc22ft** [comment]
I think it is related to the function that it is in "Resource.getSingle". But take a closer look at what you mean.
No problem with REST and HATEOAS! Forgot to comment out ... :(
