### ISSUE TITLE
No separation between logic and data

### ISSUE THREAD

**Issue by OskarKlintrot** [mc22ft/Webbramverk#23]
The code in `ResourceService` seem to be returning all data and functions together as just one large object. This is not compliant with [_Separation of concerns_](https://en.wikipedia.org/wiki/Separation_of_concerns). At least you could separate the two in an object. And also, what would happen if you get an object in return with a property called `getCollection`? Would the application crash then?

``` Javascript
// Creates a intern Resource-object that is filled with data (depending on what the server gets us)
var Resource = function(data) {
    // Configuerar objectet enligt den data som kommer in - Allt är json
    angular.extend(this, data);
};

// Get all players from the API
Resource.getCollection = function(extensionURL) {
    // Code goes here
};
```

**Comment by mc22ft** [comment]
I looked at this and do it one more time to understand what you mean.

I apologize for my error on this task. Never good to rush when you work... But you did a good job of looking at the code. I take to me what you have pointed out.

Thanks!
