### ISSUE TITLE
Destroy-metoden på userapps_controller.rb har ingen admin check

### ISSUE THREAD

**Issue by camipe** [mc22ft/Webbramverk#4]
```
class UserappsController < ApplicationController
  before_action :require_login
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

```

När issue #1 lösts så kommer administratörer ändå inte att kunna ta bort applikationer eftersom de inte körs någon koll om användaren är administratör vid borttagning. Jag har inte kunnat säkerställa att det blir så men det är slutsatsen jag drar utifrån koden.

Metoden admin_user ligger bara i users_controller.rb så den kanske borde flyttas till application_controller så den kan användas i userapps_controller.rb

**Comment by mc22ft** [comment]
Du hade en point där. 
Current_user funktionen gick till fel current_user metod därav det blev error. 

Jag gjorde som du tipsade och flyttade metoden admin_user till application_controllern la till en before_action :admin_user i min userappcontrollern.
