### ISSUE TITLE
Eventuellt förvirrande inloggningsfomulär

### ISSUE THREAD

**Issue by camipe** [mc22ft/Webbramverk#5]
Vid registrering av konton finns det 4 fält: "Namn", "Email", "Lösenord" och "Lösenord igen" men när man sedan ska logga in så finns det två fält: "Namn" och "Lösenord".

"Namn" i på inloggningssidan refererar dock till användarnamn och inte till "Namn" som på registreringssidan. Detta kan potentiellt leda till förvirring.

Förslagsvis ändras "Namn" till "Användarnamn" eller "Email" på inloggningssidan.

**Comment by mc22ft** [comment]
Du har så rätt så! Blev lite copy paste vid formulären så det slank undan radarn...
