### ISSUE TITLE
Småfixar

### ISSUE THREAD

**Issue by camipe** [mc22ft/Webbramverk#6]
Tjena,

Här kommer lite smågrejer som jag la märke till men som inte kanske inte har med om applikationen fungerar eller ej att göra.
- Vid misslyckad registrering av kontot så blandas svenska och engelska i felmeddelandena.
- Rensa bort filerna som inte används, t.ex. CSS, helpers m.m som skapas av scaffolding. Blir mer lättöverskådligt.

Spana gärna in Rubocop som någon länkade på slack, jag tyckte det var trevligt (särskilt i Atom) för att få snygg och enhetligt kod! :)

Om jag var otydlig på någon issue så hör av dig på slack eller bara via en kommentar på issuen.

/Micael

**Comment by mc22ft** [comment]
Ang registreringen, jag får inte bort: Password can't be blank, verkar flera som har lite problem med lite sökning på google. För det funkade inte att ha: :presence => {:message => 'Du måste ange ett lösenord!'} Så om du har något tips så blir jag glad...

Rensade upp lite bland filerna jag hade. Jag la in Rubycop men det verkade inte fungera. Eller det skulle "hoppa" igång efter några sekunder. Kollar mera senare på det. Tack för tips.

**Comment by mc22ft** [comment]
Håller detta issue lite öppet om jag får något tips av dig eller John :) 

Tack för rättelserna/tipsen. 

/Mathias

**Comment by camipe** [comment]
Jag använde `has_secure_password validations: false` och körde `validates :password, presence: true, length: { minimum: 8 }` i User-klassen i min applikation. Tror inte det är optimalt utan man bör nog köra något liknande som den här killen gjort: [Länk](http://vikinghammer.com/2013/02/20/rails-has-secure-password-reminder/)

Men bara man validerar att lösenordet är där på något sätt borde det vara lugnt att köra `validations: false` tror jag.

**Comment by mc22ft** [comment]
Tack för infon! :+1: 

mvh

**Comment by 1dv450** [comment]
:+1:
